batch_size: 72
batch_size: 72
burnin_steps: 100
chunk_size_test: 1800
chunk_size_train: 500
dataset: dvs_gesture
deltat: 1000
learning_rate: 1.0e-09
lr_drop_factor: 5
lr_drop_interval: 500
lc_ampl: .5
betas:
- 0.0
- 0.95
num_epochs: 4000
test_interval: 20
input_shape:
- 2
- 32
- 32
random_tau: false
reg_l:
- 0
- 0
- .5
- .5
- 1.0 #strength of regularization per layer
sim_beta: 
- .8
- .8
- .8
- .5
- .5 #strength of RS loss

