Nhid:
- 64
- 128
- 128
alpha:
- 0.97
alpharp:
- 0.65
batch_size: 1000
beta:
- 0.92
betas:
- 0.0
- 0.95
burnin_steps: 50
chunk_size_test: 300
chunk_size_train: 300
dataset: nmnist
deltat: 1000
input_shape:
- 2
- 32
- 32
kernel_size:
- 7
lc_ampl: 0.5
learning_rate: 1.0e-09
loss: smoothL1
lr_drop_factor: 5
lr_drop_interval: 500
num_epochs: 1000
num_layers: 3
optimizer: adamax
out_channels: 10
pool_size:
- 2
- 1
- 2
random_tau: false
reg_l:
- .0
- .0
- .5
- .5
test_interval: 1
