Nhid:
- 1
Mhid:
- 1000
- 1000
- 1000
batch_size: 300
batch_size_test: 300
betas:
- 0.9
- 0.999
burnin_steps: 0
chunk_size_test: 1
chunk_size_train: 1
dataset: mnist
deltat: 1000
input_shape:
- 1
- 28
- 28
kernel_size:
- 7
lc_ampl: 1.5
learning_rate: 1.0e-3
loss: ignored
lr_drop_factor: 5
lr_drop_interval: 10000
num_epochs: 30
num_conv_layers: 0
num_mlp_layers: 3
optimizer: ignored
out_channels: 10
pool_size:
- 2
- 2
random_tau: false
test_interval: 1
