Nhid:
- 1
Mhid:
- 1000
- 1000
- 1000
batch_size: 100
batch_size_test: 10000
betas:
- 0.9
- 0.999
burnin_steps: 100
chunk_size_test: 1
chunk_size_train: 1
dataset: mnist
deltat: 1000
input_shape:
- 1
- 28
- 28
kernel_size:
- 7
lc_ampl: 1.5
learning_rate: 1.0e-3
loss: nn.CrossEntropyLoss
lr_drop_factor: 5
lr_drop_interval: 10000
num_epochs: 60000
num_conv_layers: 0
num_mlp_layers: 3
optimizer: adam
out_channels: 10
pool_size:
- 2
- 2
random_tau: false
test_interval: 1000
